version: '3'
services:

  frontend: 
      image: 392447683797.dkr.ecr.us-east-1.amazonaws.com/blog-app:1.0
      ports: 
        - "4200:4200"

  backend:
      image: backend:1.0
      ports:
        - "3000:3000"
